### PR TITLE
[volume] add cinder upload-to-image

### PR DESCRIPTION
**Pull request by stefanymarie**

### CODE REVIEW

**Comment by stefanymarie** [comment]
```
usage: cinder upload-to-image [--force <True|False>]
                              [--container-format <container-format>]
                              [--disk-format <disk-format>]
                              <volume> <image-name>

Uploads volume to Image Service as an image.

Positional arguments:
  <volume>              Name or ID of volume to snapshot.
  <image-name>          The new image name.

Optional arguments:
  --force <True|False>  Enables or disables upload of a volume that is
                        attached to an instance. Default=False.
  --container-format <container-format>
                        Container format type. Default is bare.
  --disk-format <disk-format>
                        Disk format type. Default is raw.
```

**Comment by choodur** [comment]
https://wiki.openstack.org/wiki/CreateVolumeFromImage

**Comment by choodur** [comment]
:+1:  Looks good to me.

**Comment by lvillasica** [comment]
+1

**Pull request merged**
